//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalMediaLibraryData
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileInDb
    {
        public int FileInDbId { get; set; }
        public string Name { get; set; }
        public string Expansion { get; set; }
        public string DateOfCreation { get; set; }
        public string Size { get; set; }
        public byte[] FileSourse { get; set; }
        public int CategoryId { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
